apiVersion: v1beta1
kind:  ReplicationController
id: kibana-logging-controller
desiredState:
  replicas: 1
  replicaSelector:
    name: kibana-logging
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: kibana-viewer
        containers:
          - name: kibana-logging
            image: qdco.chinacloudapp.cn:5000/kibana:1.2
            env: 
              - name: "ES_SCHEME"
                value: "http"
              - name: "ES_HOST"
                value: "\"+window.location.hostname+\":9200"
            ports:
              - name: kibana-port
                containerPort: 80
    labels:
      name: kibana-logging
      kubernetes.io/cluster-service: "true"
labels:
  name: kibana-logging
  kubernetes.io/cluster-service: "true"
